### PR TITLE
Upgrade Envoy gRPC API to V3

### PR DESCRIPTION
**Pull request by mihaitodor**
This seems to work with Envoy v1.21.1 (at least I can see what I'm expecting in Envoy UI).

<details>
<summary>Sample Envoy config for backends</summary>

```yaml
admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

dynamic_resources:
  ads_config:
    api_type: GRPC
    transport_api_version: V3
    grpc_services:
      - envoy_grpc:
          cluster_name: xds_cluster
  cds_config:
    resource_api_version: V3
    ads: {}
  lds_config:
    resource_api_version: V3
    ads: {}

static_resources:
  clusters:
    - name: xds_cluster
      connect_timeout: 0.25s # Default 5s
      type: STATIC
      lb_policy: ROUND_ROBIN
      http2_protocol_options: {}
      upstream_connection_options:
        # configure a TCP keep-alive to detect and reconnect to the admin
        # server in the event of a TCP socket half open connection
        tcp_keepalive: {}
      load_assignment:
        cluster_name: xds_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 7776
```

</details>

TODO:
- [x] Fix tests a bit more
- [ ] Proper testing
- [ ] Ingress config generator
- [ ] Run end-to-end tests with SSL enabled

### CODE REVIEW

**Comment by relistan** [comment]
I still have not gotten around to testing this. We will look at it in late summer. Thanks again @mihaitodor !

**Comment by mihaitodor** [comment]
Take your time @relistan. Happy to help with the testing & deployment. Just let me know :) I have the latest test harness here if more quick experiments are needed: https://github.com/mihaitodor/sidecar_demo

**Comment by danpilch** [comment]
hey @mihaitodor thanks for spending time on this, I am starting to get my head around finally upgrading community's envoy stack as we're stuck on v1.15.x which is now really old. We made a lot of changes to sidecar in the past year to support k8s but I don't think your changes here would affect that. I don't suppose you could please rebase your branch against master? Then I can try test it out. Thank you

**Comment by mihaitodor** [comment]
Hey @danpilch Let's go with your PR. Feel free to close this one.

**Pull request closed without merging**
